version: '3'
services:
        webserver:
                image: nginx:latest
                container_name: webserver
                volumes: 
                - ./html/:/usr/share/nginx/html:ro
                ports: 
                - 8080:80
                  #networks:
                  #default:
                  #external#:
                  #name: webdmz
